version: '3.8'

services:
  app:
    image: yanau/hl:1.0
    container_name: museum-app
    deploy:
      resources:
        limits:
          cpus: "${APP_CPU_LIMIT}"
          memory: ${LIMITS_MEM}
        reservations:
          cpus: "${RESERV_CPU}"
          memory: ${RESERV_MEM}
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SERVER_TOMCAT_MAX_THREADS=${TOMCAT_MAX_THREADS}
      - SERVER_TOMCAT_MIN_SPARE_THREADS=${TOMCAT_MIN_SPARE_THREADS}
      - SPRING_JPA_SHOW_SQL=${SHOW_SQL}
      - SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL=false

      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9094
      - APP_KAFKA_CONCURRENCY=${APP_KAFKA_CONCURRENCY}
    extra_hosts:

      - "host.docker.internal:host-gateway"
      - "hl15.zil:host-gateway"
      - "hl14.zil:host-gateway"
      - "hl15:host-gateway"
      - "hl14:host-gateway"
 
  additional:
    image: yanau/museum-additional:1.0
    container_name: museum_additional
    deploy:
      resources:
        limits:
          cpus: "${APP_CPU_LIMIT}"
          memory: ${ADDITIONAL_LIMITS_MEM}
        reservations:
          cpus: "${ADDITIONAL_RESERV_CPU}"
          memory: ${ADDITIONAL_RESERV_MEM}
    ports:
      - "8081:8081"
    environment:
      - CRUD_SERVICE_URL=http://museum-app:8080
    depends_on:
      - app