apiVersion: v1
kind: Service
metadata:
  name: museum-additional-nodeport
  namespace: hl08
spec:
  type: NodePort
  selector:
    app: museum-additional
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 30083  