apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: museum-additional-hpa
  namespace: hl08
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: museum-additional
  minReplicas: 1
  maxReplicas: 3  
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 20  
      policies:
        - type: Pods
          value: 1
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 60  
      policies:
        - type: Pods
          value: 1
          periodSeconds: 30
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 30 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 40
  