spring.application.name=module1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL}
spring.flyway.enabled=true



spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

server.tomcat.max-threads=${TOMCAT_MAX_THREADS}
server.tomcat.min-spare-threads=${TOMCAT_MIN_SPARE_THREADS}
server.tomcat.mbeanregistry.enabled=true
management.endpoints.web.exposure.include=health,info,metrics

observability.window.short=10
observability.window.medium=30
observability.window.long=60
observability.schedule.ms=10000