spring.application.name=module1
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=${SHOW_SQL}
spring.flyway.enabled=true
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

server.tomcat.max-threads=${TOMCAT_MAX_THREADS}
server.tomcat.min-spare-threads=${TOMCAT_MIN_SPARE_THREADS}
server.tomcat.mbeanregistry.enabled=true
management.endpoints.web.exposure.include=health,info,metrics
